name: Terraform OIDC Deploy

on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: "Igor_Terraform"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "terraform-aws"
  CONFIG_DIRECTORY: "./terraform-code"

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    permissions: 
      id-token: write    # Obrigatório para emitir token OIDC
      contents: read     # Necessário para clonar o repositório

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4
      
      - name: Exibir arquivos no repositório raiz
        run: ls -lR

      - name: Verificar conteúdo do diretório Terraform
        run: ls -l
        working-directory: ./terraform-code

      - name: Verificar variáveis TF disponíveis
        working-directory: ./terraform-code
        run: |
          echo "TF_API_TOKEN -> ${TF_API_TOKEN}"
          echo "TF_TOKEN_app_terraform_io -> ${TF_TOKEN_app_terraform_io}"  

      - name: Configurar credenciais da AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::471112695892:role/Terraform-Role
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: ./terraform-code
        

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform-code