name: Terraform OIDC Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    

    permissions: 
      id-token: write    # Obrigat칩rio para emitir token OIDC
      contents: read     # Necess치rio para clonar o reposit칩rio

    steps:
      - name: Checkout reposit칩rio
        uses: actions/checkout@v4

      - name: Mostrar token OIDC (debug opcional)
        id: oidc-token
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken();
            console.log("TOKEN OIDC:", token);

      - name: Configurar credenciais da AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::471112695892:role/Terraform-Role
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-code

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform-code